name: Slack notification on job failure
on: push
jobs:
  slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Success job
        run: exit 0
      - name: Slack notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
